# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f2f844fb3fe12ccdc26b7157dd2c5607"
name = "3d Print Integration"
handle = "3d-print-integration"
application_url = "https://shopzilla-along-bargains-beast.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "3d-print-integration.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shopzilla-along-bargains-beast.trycloudflare.com/auth/callback",
  "https://shopzilla-along-bargains-beast.trycloudflare.com/auth/shopify/callback",
  "https://shopzilla-along-bargains-beast.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
